### ISSUE TITLE
Flickering Issue in Waterfall

### ISSUE THREAD

**Issue by Steven9101** [PhantomSDR/frontend#2]
The waterfall flickers, i already looked over it couldnt find the issue right now. Ill look again tomorrow, seems to be either no synchronized properly or something else. 

Heres an gif of it
![chrome_V85tieTLnB](https://github.com/PhantomSDR/frontend/assets/164558083/cedf6013-ed1a-4a9b-9a3f-87294edb691d)

**Comment by rhgndf** [comment]
This is probably because of subpixel scrolling. Realised I had forgotten to push this commit: d601ce9dc2ac3e994fe2896197e7a483be2f6792. That should fix it.

**Comment by Steven9101** [comment]
Still seems to be there even after the commit. 
![chrome_1Jol65Boef](https://github.com/PhantomSDR/frontend/assets/164558083/d69e1482-dcbc-44f1-8983-962a0140a0f0)

**Comment by Steven9101** [comment]
It also has to do something with scaling i guess because when the waterfall is smaller it gets more (when opening developer console and dragging it more to the left). 
![chrome_JvFO23XZoK](https://github.com/PhantomSDR/frontend/assets/164558083/c4f55cfd-a7fa-4782-a149-8b120f954949)

**Comment by Steven9101** [comment]
Keep me updated of when you have news.

**Comment by rhgndf** [comment]
I tried using the native display pixel resolution instead with this: 0e64a0d. That should fix it. Are you using it on a HiDPI screen?

**Comment by rhgndf** [comment]
I'm not able to reproduce it fully so this is sort of my best guess.

**Comment by Steven9101** [comment]
Ill try it but i dont think i use an hidpi screen. Tried on 2k screen and on 24 inch normal 1080p screen dont think the 1080 is hidpi

**Comment by rhgndf** [comment]
The new code should take into account for that, resizing the canvas for screens both non-hidpi and hidpi.
