### ISSUE TITLE
Performance Optimization on lower end devices.

### ISSUE THREAD

**Issue by Steven9101** [PhantomSDR/frontend#3]
It needs to be more optimized on mobile devices, and low performance devices. Especially the waterfall drag performance etc. Also the filter curve has to be more easy to drag and seperated from the frequency dragging. Also resizing is broken after your update. As you can see on websdr the waterfall drag performance is quicker and also works good on mobile devices and on low performance devices (the waterfall is smaller). Maybe that could be possible to do.

**Comment by Steven9101** [comment]
Also i think this is more on the main repo than here but the waterfall not always has the full quality and some zoom levels just look horrible because of low quality. I think every zoom step should be full quality from the server.

**Comment by rhgndf** [comment]
This commit sends slightly higher quality version of the waterfall: [4f0c8d5](https://github.com/PhantomSDR/PhantomSDR/commit/4f0c8d5d57d14db3751bf2ec52fade250264593e)

This commit 8a33b51 improves the mobile UI.

**Comment by rhgndf** [comment]
Resize: I will need to work through this a bit since it is not very simple to implement.

Performance: This waterfall is around 10 times bigger than the websdr one, so some slowdown is to be expected. I am investigating how to speed it up.

**Comment by rhgndf** [comment]
147a925 This adds resize functionality.

**Comment by Steven9101** [comment]
Yea but when zooming to far it breaks now, max zoom doesnt work for me. Also resizing i think only works once and then breaks but im unsure. Havent tested that enough yet.

**Comment by Steven9101** [comment]
Sometimes it works and sometimes when zooming in the waterfall just disappears, but i know why that happens. Thats because the zoom button zooms more than is possible. Max is less than you can zoom with the + button
