### ISSUE TITLE
Filter moves when moving frequency line

### ISSUE THREAD

**Issue by Steven9101** [PhantomSDR/frontend#4]
The filter changes when you move the frequency line and not the filter min max, so you basically cant drag it.

You can see it on my receiver https://sdr-list.xyz

**Comment by Steven9101** [comment]
Also i implemented Network Kbits i dont know if i should do a PR because you said it should be multi-os, this way can be used on any OS as i just use the Bytes sent

**Comment by Steven9101** [comment]
Also with the filter it even happens when clicking i think.

**Comment by rhgndf** [comment]
Is it fixed in the latest commit?

As for the Network Kbits, you could do a PR and I could try to see whether it could be made multi-os.

**Comment by Steven9101** [comment]
It is multi os, we just count the bits and convert to bytes
